-- Habitly by PRK: small visitor registry + private admin access.
-- Run this in Supabase SQL Editor after creating your project.

create table if not exists public.visitors (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 80),
  email text not null check (char_length(email) between 3 and 160),
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  visit_count integer not null default 1 check (visit_count > 0)
);

create unique index if not exists visitors_email_lower_idx on public.visitors (lower(email));

create table if not exists public.user_roles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role text not null check (role in ('admin'))
);

alter table public.visitors enable row level security;
alter table public.user_roles enable row level security;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.user_roles
    where user_id = auth.uid() and role = 'admin'
  );
$$;



alter table public.user_roles enable row level security;

drop policy if exists "public may register visitors" on public.visitors;
create policy "public may register visitors" on public.visitors
for insert to anon, authenticated with check (true);

drop policy if exists "admins may read visitors" on public.visitors;
create policy "admins may read visitors" on public.visitors
for select to authenticated using (public.is_admin());

drop policy if exists "admins may update visitors" on public.visitors;
create policy "admins may update visitors" on public.visitors
for update to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "users may read own role" on public.user_roles;
create policy "users may read own role" on public.user_roles
for select to authenticated using (auth.uid() = user_id);

grant insert on public.visitors to anon, authenticated;
grant select, update on public.visitors to authenticated;

grant select on public.user_roles to authenticated;

-- Create the admin user in Supabase Authentication first.
-- Then replace ADMIN_USER_UUID below with that user's UUID and run:
-- insert into public.user_roles(user_id, role) values ('ADMIN_USER_UUID', 'admin');

grant execute on function public.is_admin() to anon, authenticated;

create or replace function public.register_visitor(p_name text, p_email text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare existing_id bigint;
begin
  select id into existing_id from public.visitors where lower(email) = lower(trim(p_email)) limit 1;
  if existing_id is null then
    insert into public.visitors(name,email) values (trim(p_name),lower(trim(p_email)));
  else
    update public.visitors
      set name = trim(p_name), last_seen_at = now(), visit_count = visit_count + 1
      where id = existing_id;
  end if;
end;
$$;

grant execute on function public.register_visitor(text,text) to anon, authenticated;


-- ============================================================
-- Habitly realtime synchronization
-- ============================================================
-- One authenticated row per Habitly account. The browser keeps the
-- working copy + durable mutation queue locally; this row is the
-- revisioned cloud synchronization document. Google Drive remains
-- an independent backup/restore layer.
create table if not exists public.habitly_sync_documents (
  user_id uuid primary key references auth.users(id) on delete cascade,
  revision bigint not null check (revision >= 1),
  state jsonb not null,
  updated_at timestamptz not null default now(),
  updated_by text not null,
  constraint habitly_sync_state_object check (jsonb_typeof(state) = 'object')
);

alter table public.habitly_sync_documents enable row level security;

drop policy if exists "users may read own Habitly sync document" on public.habitly_sync_documents;
create policy "users may read own Habitly sync document"
on public.habitly_sync_documents
for select to authenticated
using (auth.uid() = user_id);

drop policy if exists "users may insert own Habitly sync document" on public.habitly_sync_documents;
create policy "users may insert own Habitly sync document"
on public.habitly_sync_documents
for insert to authenticated
with check (auth.uid() = user_id);

drop policy if exists "users may update own Habitly sync document" on public.habitly_sync_documents;
create policy "users may update own Habitly sync document"
on public.habitly_sync_documents
for update to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

grant select, insert, update on public.habitly_sync_documents to authenticated;

-- The database clock is authoritative for cloud commit time. Client clocks can
-- differ substantially between a phone and a laptop, so updated_at must never
-- be used as the cross-device ordering primitive. The revision CAS above is the
-- ordering primitive; this trigger only makes the audit timestamp trustworthy.
create or replace function public.habitly_sync_set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists habitly_sync_documents_set_updated_at on public.habitly_sync_documents;
create trigger habitly_sync_documents_set_updated_at
before update on public.habitly_sync_documents
for each row execute function public.habitly_sync_set_updated_at();

grant execute on function public.habitly_sync_set_updated_at() to authenticated;

-- Supabase Realtime must be able to observe this table. The command is
-- idempotent when the table is already a member of the publication.
do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'habitly_sync_documents'
  ) then
    alter publication supabase_realtime add table public.habitly_sync_documents;
  end if;
end $$;
