-- Habitly production cloud sync schema (v2)
--
-- Architecture:
--   Browser local state -> durable mutation queue -> Supabase authoritative state
--   -> Supabase Realtime -> other devices
--   Google Drive is backup/restore only and is never an active sync source.
--
-- IMPORTANT: this intentionally uses a NEW table name so a fresh Habitly install
-- does not inherit the old Drive-era synchronization document.

-- Existing visitor/admin objects used by the application.
create table if not exists public.visitors (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 80),
  email text not null check (char_length(email) between 3 and 160),
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  visit_count integer not null default 1 check (visit_count > 0)
);
create unique index if not exists visitors_email_lower_idx on public.visitors (lower(email));

create table if not exists public.user_roles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role text not null check (role in ('admin'))
);

alter table public.visitors enable row level security;
alter table public.user_roles enable row level security;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.user_roles
    where user_id = auth.uid() and role = 'admin'
  );
$$;

grant execute on function public.is_admin() to anon, authenticated;

drop policy if exists "public may register visitors" on public.visitors;
create policy "public may register visitors" on public.visitors
for insert to anon, authenticated with check (true);

drop policy if exists "admins may read visitors" on public.visitors;
create policy "admins may read visitors" on public.visitors
for select to authenticated using (public.is_admin());

drop policy if exists "admins may update visitors" on public.visitors;
create policy "admins may update visitors" on public.visitors
for update to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "users may read own role" on public.user_roles;
create policy "users may read own role" on public.user_roles
for select to authenticated using (auth.uid() = user_id);

grant insert on public.visitors to anon, authenticated;
grant select, update on public.visitors to authenticated;
grant select on public.user_roles to authenticated;


create or replace function public.register_visitor(p_name text, p_email text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare existing_id bigint;
begin
  select id into existing_id from public.visitors where lower(email) = lower(trim(p_email)) limit 1;
  if existing_id is null then
    insert into public.visitors(name,email) values (trim(p_name),lower(trim(p_email)));
  else
    update public.visitors
      set name = trim(p_name), last_seen_at = now(), visit_count = visit_count + 1
      where id = existing_id;
  end if;
end;
$$;

grant execute on function public.register_visitor(text, text) to anon, authenticated;

-- ============================================================
-- Habitly authoritative cloud state v2
-- ============================================================
create table if not exists public.habitly_sync_documents_v2 (
  user_id uuid primary key references auth.users(id) on delete cascade,
  revision bigint not null check (revision >= 1),
  state jsonb not null,
  updated_at timestamptz not null default now(),
  updated_by text not null,
  constraint habitly_sync_v2_state_object check (jsonb_typeof(state) = 'object')
);

alter table public.habitly_sync_documents_v2 enable row level security;

drop policy if exists "users may read own Habitly v2 sync document" on public.habitly_sync_documents_v2;
create policy "users may read own Habitly v2 sync document"
on public.habitly_sync_documents_v2
for select to authenticated
using (auth.uid() = user_id);

-- Writes are intentionally NOT granted directly. The atomic RPC below is the
-- only mutation path. This prevents a client from bypassing revision checks.
revoke insert, update, delete on public.habitly_sync_documents_v2 from anon, authenticated;
grant select on public.habitly_sync_documents_v2 to authenticated;

-- Atomic compare-and-swap commit.
-- expected_revision = 0 means "create if absent".
-- Any mismatch raises a conflict and the browser refetches/rebases its pending
-- mutations. The database revision, not client timestamps, is the ordering
-- primitive.
create or replace function public.commit_habitly_sync_v2(
  p_expected_revision bigint,
  p_state jsonb,
  p_device_id text
)
returns public.habitly_sync_documents_v2
language plpgsql
security definer
set search_path = public
as $$
declare
  uid uuid := auth.uid();
  current_revision bigint;
  result_row public.habitly_sync_documents_v2;
begin
  if uid is null then
    raise exception 'Authentication required';
  end if;

  if p_state is null or jsonb_typeof(p_state) <> 'object' then
    raise exception 'Habitly state must be a JSON object';
  end if;

  if p_device_id is null or char_length(trim(p_device_id)) < 3 then
    raise exception 'Invalid Habitly device id';
  end if;

  select revision into current_revision
  from public.habitly_sync_documents_v2
  where user_id = uid
  for update;

  if current_revision is null then
    if coalesce(p_expected_revision, 0) <> 0 then
      raise exception 'HABITLY_CONFLICT: cloud document was created by another device';
    end if;

    insert into public.habitly_sync_documents_v2(user_id, revision, state, updated_at, updated_by)
    values (uid, 1, p_state, now(), trim(p_device_id))
    returning * into result_row;
    return result_row;
  end if;

  if current_revision <> coalesce(p_expected_revision, 0) then
    raise exception 'HABITLY_CONFLICT: expected revision %, actual revision %', p_expected_revision, current_revision;
  end if;

  update public.habitly_sync_documents_v2
     set revision = current_revision + 1,
         state = p_state,
         updated_at = now(),
         updated_by = trim(p_device_id)
   where user_id = uid
   returning * into result_row;

  return result_row;
end;
$$;

revoke all on function public.commit_habitly_sync_v2(bigint, jsonb, text) from public;
grant execute on function public.commit_habitly_sync_v2(bigint, jsonb, text) to authenticated;

-- Realtime needs the table in the publication. RLS on the table ensures each
-- authenticated subscriber only receives its own row.
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'habitly_sync_documents_v2'
  ) then
    alter publication supabase_realtime add table public.habitly_sync_documents_v2;
  end if;
end $$;
